spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres
    username: postgres
    password: postgres

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:54321/auth/v1/.well-known/jwks.json
          jws-algorithms: ES256

app:
  cors:
    allowed-origins: http://localhost:4200

management:
  endpoint:
    health:
      show-details: always
